--ASSIGNEMENT ON MRF

CREATE TABLE EMP (
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(50),
    JOB VARCHAR(30),
    MGR INT,
    HIREDATE DATE,
    SAL DECIMAL(10,2),
    COMM DECIMAL(10,2),
    DEPTNO INT
);

INSERT INTO EMP VALUES (7369, 'SMITH', 'CLERK', 7902, '1980-12-17', 800, NULL, 20);
INSERT INTO EMP VALUES (7499, 'ALLEN', 'SALESMAN', 7698, '1981-02-20', 1600, 300, 30);
INSERT INTO EMP VALUES (7521, 'WARD', 'SALESMAN', 7698, '1981-02-22', 1250, 500, 30);
INSERT INTO EMP VALUES (7566, 'JONES', 'MANAGER', 7839, '1981-04-02', 2975, NULL, 20);
INSERT INTO EMP VALUES (7654, 'MARTIN', 'SALESMAN', 7698, '1981-09-28', 1250, 1400, 30);
INSERT INTO EMP VALUES (7698, 'BLAKE', 'MANAGER', 7839, '1981-05-01', 2850, NULL, 30);
INSERT INTO EMP VALUES (7782, 'CLARK', 'MANAGER', 7839, '1981-06-09', 2450, NULL, 10);
INSERT INTO EMP VALUES (7788, 'SCOTT', 'ANALYST', 7566, '1982-12-09', 3000, NULL, 20);
INSERT INTO EMP VALUES (7839, 'KING', 'PRESIDENT', NULL, '1981-11-17', 5000, NULL, 10);
INSERT INTO EMP VALUES (7844, 'TURNER', 'SALESMAN', 7698, '1981-09-08', 1500, 0, 30);
INSERT INTO EMP VALUES (7876, 'ADAMS', 'CLERK', 7788, '1983-01-12', 1100, NULL, 20);
INSERT INTO EMP VALUES (7900, 'JAMES', 'CLERK', 7698, '1981-12-03', 950, NULL, 30);
INSERT INTO EMP VALUES (7902, 'FORD', 'ANALYST', 7566, '1981-12-03', 3000, NULL, 20);
INSERT INTO EMP VALUES (7934, 'MILLER', 'CLERK', 7782, '1982-01-23', 1300, NULL, 10);

CREATE TABLE DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(50),
    LOC VARCHAR(50)
);

INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');

--1.WAQTD NUMBER OF EMPLOYEES GETTING SALARY LESS THAN 2000 IN DEPTNO 10. 
SELECT * FROM EMP
WHERE SAL<2000 AND DEPTNO =10;

--2.WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES WORKING AS CLERK.
SELECT SUM(SAL) AS TOTAL_SALARY FROM EMP
WHERE JOB ='CLERK';

--3.WAQTD AVERAGE SALARY NEEDED TO PAY ALL EMPLOYEES. 
SELECT AVG(SAL) AS AVERAGE_SALARY FROM EMP;

--4.WAQTD NUMBER OF EMPLOYEES HAVING 'A' AS THEIR FIRST CHARACTER. 
SELECT ENAME FROM EMP
WHERE ENAME LIKE 'A%';

--5.WAQTD NUMBER OF EMPLOYEES WORKING AS CLERK OR MANAGER. 
SELECT COUNT(*) FROM EMP
WHERE JOB IN ('CLERK' , 'MANAGER');

--6.WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES HIRED IN FEB. 
SELECT SUM(SAL) AS SALARY FROM EMP
WHERE MONTH(HIREDATE) = '02';

--7.WAQTD NUMBER OF EMPLOYEES REPORTING TO 7839 (MGR). 
SELECT * FROM EMP
WHERE MGR = 7839;

--8.WAQTD NUMBER OF EMPLOYEES GETTING COMISSION IN DEPTNO 30. 
SELECT * FROM EMP
WHERE COMM>0 AND DEPTNO = 30;

--9.WAQTD AVG SAL , TOTAL SAL , NUMBER OF EMPS AND MAXIMUM SALARY GIVEN TO EMPLOYEES WORKING AS PERSIDENT. 
SELECT AVG(SAL) AS AVERGAE_SALARY,SUM(SAL) AS TOTAL_SALARY,COUNT(*) AS NUMBER_OF_EMPS,MAX(SAL) AS MAXIMUM_SALARY FROM EMP;

--10.WAQTD NUMBER OF EMPLOYEES HAVING 'A' IN THEIR NAMES. 
SELECT ENAME FROM EMP
WHERE ENAME LIKE '%A%';
 
--11.WAQTD NUMBER OF EMPS AND TOTAL SALARY NEEDED TO PAY THE EMPLOYEES WHO HAVE 2 CONSICUTIVE L's IN THEIR NAMES. 
SELECT COUNT(*) AS EMPS,SUM(SAL) AS SALARY FROM EMP
WHERE ENAME LIKE '%LL%';

--12.WAQTD NUMBER OF DEPARTMENTS PRESENT IN EMPLOYEE TABLE. 
SELECT COUNT(DISTINCT DEPTNO) AS DEPT FROM EMP;

--13.WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'Z' IN THEIR NAMES. 
SELECT ENAME FROM EMP
WHERE ENAME LIKE '%Z%';

--14.WAQTD NUMBER OF EMPLOYEES HAVING '$' IN THEIR NAMES.  
SELECT ENAME FROM EMP
WHERE ENAME LIKE '%$%';

--15.WAQTD TOTAL SALARY GIVEN TO EMPLOYEES WORKING AS CLERK IN DEPT 30. 
SELECT SUM(SAL) AS SALARY  FROM EMP
WHERE JOB= 'CLERK' AND DEPTNO = 30;

--16.WAQTD MAXIMUM SALARY GIVEN TO THE EMPLOYEES WORKING AS ANALYST. 
SELECT MAX(SAL) FROM EMP
WHERE JOB ='ANALYST';

--17.WAQTD NUMBER OF DISTINCT SALARIES PRESENT IN EMPLOYEE TABLE. 
SELECT COUNT(DISTINCT SAL) AS DISTINCT_SALARIES
FROM EMP;

--18.WAQTD NUMBER OF JOBS PRESENT IN EMPLOYEE TABLE. 
SELECT COUNT(DISTINCT JOB) AS DISTICENT_JOBS FROM EMP;

--19.WATQD AVG SALARY GIVEN TO THE CLERK. 
SELECT AVG(SAL) AS AVG_SALARY FROM EMP
WHERE JOB= 'CLERK';

--20.WAQTD MINIMUM SALARY GIVEN TO THE EMPLOYEES WHO WORK IN DEPT 10 AS MANAGER  OR A CLERK.
SELECT MIN(SAL) AS MIN_SALARY FROM EMP
WHERE DEPTNO =10 AND JOB IN ('MANAGER','CLERK');
