-- ASSIGNMENT ON EMP AND DEPT TABLE: 

CREATE TABLE EMPLOYEE(
EMP_ID INT PRIMARY KEY,
    ENAME VARCHAR(50),
    JOB VARCHAR(50),
    SALARY INT,
    COMMISSION INT,
    DEPT_NO INT,
    HIREDATE DATE
);

CREATE TABLE DEPT (
    DEPT_NO INT PRIMARY KEY,
    DNAME VARCHAR(50),
    LOCATION VARCHAR(50)
);


INSERT INTO EMPLOYEE VALUES
(101, 'Ravi', 'Manager', 50000, 5000, 10, '2020-01-15'),
(102, 'Sita', 'Clerk', 25000, NULL, 20, '2021-03-10'),
(103, 'Amit', 'Analyst', 40000, 2000, 10, '2019-07-23'),
(104, 'Neha', 'Salesman', 30000, 3000, 30, '2022-05-30');

INSERT INTO DEPT VALUES
(10, 'HR', 'Hyderabad'),
(20, 'Finance', 'Mumbai'),
(30, 'Sales', 'Chennai');

-- 1. WRITE A QUERY TO DISPLAY ALL  THE DETAILS FROM THE EMPLOYEE TABLE. 
SELECT * FROM EMPLOYEE;

-- 2. WAQTD NAMES OF ALL THE EMPLOYEES. 
SELECT ENAME FROM EMPLOYEE;

--3. WAQTD NAME AND SALARY GIVEN TO ALL THE EMPLOYEES.
SELECT ENAME,SALARY FROM EMPLOYEE;

--4. WAQTD NAME AND COMMISSION GIVEN TO ALL THE EMPLOYEES.
SELECT ENAME,COMMISSION FROM EMPLOYEE;

--5. WAQTD EMPLOYEE ID AND DEPARTMENT NUMBER OF ALL THE EMPLOYEES IN EMP TABLE.
SELECT ENAME,DEPT_NO FROM EMPLOYEE;

--6. WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEES . 
SELECT ENAME,HIREDATE FROM EMPLOYEE;

--7. WAQTD NAME AND DESIGNATION OF ALL THE EMPLPOYEES . 
SELECT ENAME,JOB FROM EMPLOYEE;

--8. WAQTD NAME , JOB AND SALARY GIVEN ALL THE EMPLOYEES. 
SELECT ENAME,JOB,SALARY FROM EMPLOYEE;

--9. WAQTD DNAMES PRESENT IN DEPARTMENT TABLE. 
SELECT DNAME FROM DEPT;

--10. WAQTD DNAME AND LOCATION PRESENT IN DEPT TABLE.
SELECT DNAME,LOCATION FROM DEPT;



-- ASSIGNMENT ON EXPRESSION & ALIAS 

--1.WAQTD NAME OF THE EMPLOYEE ALONG WITH THEIR ANNUAL SALARY.
SELECT ENAME,SALARY *12 AS ANNUAL_SALARY FROM EMPLOYEE;

--2.WAQTD ENAME AND JOB FOR ALL THE EMPLOYEE WITH THEIR HALF TERM SALARY.  
SELECT ENAME,JOB,SALARY/2 AS HALF_TERM_SALARY FROM EMPLOYEE;

--3.WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH AN ANNUALBONUS OF 2000.
SELECT *,2000 AS ANNUALBONUS FROM EMPLOYEE;

--4.WAQTD NAME SALARY AND SALARY WITH A HIKE OF 10%. 
SELECT ENAME,SALARY,SALARY/10 AS HIKE,SALARY+(salary/10) AS TOTAL FROM EMPLOYEE;

--5.WAQTD NAME AND SALARY WITH DEDUCTION OF 25%.
SELECT ENAME,SALARY,SALARY-(SALARY/25) AS DEDUCTION FROM EMPLOYEE;

--6.WAQTD NAME AND SALARY WITH  MONTHLY HIKE OF 50.
SELECT ENAME,SALARY,SALARY+50 AS MONTHLY_HIKE FROM EMPLOYEE;

--7.WAQTD NAME AND ANNUAL SALARY WITH DEDUCTION OF 10%.
SELECT ENAME,(SALARY*12)/10 AS ANNUALSALARY_WITH_DEDUCTION FROM EMPLOYEE;

--8.WAQTD TOTAL SALARY GIVEN TO EACH EMPLOYEE (SAL+COMM). 
SELECT ENAME,SALARY,COMMISSION,SALARY+COMMISSION AS "SAL+COM" FROM EMPLOYEE;

--9.WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH ANNUAL SALARY.
SELECT *,SALARY*12 AS 'ANNUAL SALARY' FROM EMPLOYEE;

--10.WAQTD NAME AND DESIGNATION ALONG WITH 100 PENALTY IN SALARY.
SELECT ENAME,JOB,SALARY-100 AS 'PENALATY' FROM EMPLOYEE;


-- ASSIGNMENT ON WHERE CLAUSE .

--1.WAQTD THE ANNUAL SALARY OF THE EMPLOYEE WHOS NAME IS SITA 
SELECT ENAME,SALARY*12 AS 'ANNUAL SALARY' FROM EMPLOYEE
WHERE ENAME = 'Sita';

--2.WAQTD NAME OF THE EMPLOYEES WORKING AS HR
SELECT ENAME FROM EMPLOYEE
JOIN DEPT
ON EMPLOYEE.DEPT_NO=DEPT.DEPT_NO
WHERE DNAME ='HR';

--3.WAQTD SALARY OF THE EMPLOYEES WHO ARE WORKING AS SALES
SELECT ENAME,SALARY FROM EMPLOYEE
JOIN DEPT
ON EMPLOYEE.DEPT_NO =DEPT.DEPT_NO
WHERE DNAME ='SALES';

--4.WAQTD DETAILS OF THE EMP WHO EARNS MORE THAN 2000 
SELECT * FROM EMPLOYEE
WHERE SALARY>2000;

--5.WAQTD DETAILS OF THE EMP WHOS NAME IS RAVI
SELECT * FROM EMPLOYEE
WHERE ENAME ='RAVI';

--6.WAQTD DETAILS OF THE EMP WHO WAS HIRED AFTER 01-JAN-21
SELECT * FROM EMPLOYEE
WHERE HIREDATE >'2021-01-01';

--7.WAQTD NAME AND SAL ALONG WITH HIS ANNUAL SALARY IF THE ANNUAL SALARY IS MORE THAN 4,00,000
SELECT ENAME,SALARY,SALARY*12 AS 'ANNUAL SALARY' FROM EMPLOYEE
WHERE SALARY*12 >400000;

--8.WAQTD EMPNO OF THE EMPLOYEES WHO ARE WORKING IN DEPT 30 
SELECT * FROM EMPLOYEE
WHERE DEPT_NO =30;

--9.WAQTD ENAME AND HIREDATE IF THEY ARE HIRED BEFORE 2020
SELECT ENAME,HIREDATE FROM EMPLOYEE
WHERE YEAR(HIREDATE) >'2020';

-- 10.WAQTD DETAILS OF THE EMPLOYEES WORKING AS Finance
SELECT * FROM EMPLOYEE
JOIN DEPT
ON EMPLOYEE.DEPT_NO=DEPT.DEPT_NO
WHERE DNAME='Finance';

--11.WAQTD NAME AND SALARY GIVEN TO AN EMPLOYEE IF EMPLOYEE EARNS A COMMISSION OF RUPEES 3000  
SELECT ENAME,SALARY FROM EMPLOYEE
WHERE COMMISSION = 3000;

--12.WAQTD DETAILS OF EMPLOYEES HAVING COMMISSION MORE THAN SALARY 
SELECT * FROM EMPLOYEE
WHERE COMMISSION >SALARY;

--13.WAQTD EMPNO OF EMPLOYEES HIRED BEFORE THE YEAR 2020
SELECT EMP_ID,HIREDATE FROM EMPLOYEE
WHERE YEAR(HIREDATE) <2020;

--14.WAQTD DETAILS OF EMPLOYEES WORKING AS AN  ANALYST
SELECT * FROM EMPLOYEE
WHERE JOB = 'ANALYST';

--15.WAQTD DETAILS OF EMPS EARNING MORE THAN 2000 RUPEES PER MONTH 
SELECT * FROM EMPLOYEE
WHERE SALARY >2000;


-- ASSIGNMENT ON LOGICAL OPERATORS :

--1.WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND EARNING LESS THAN 1500. 
SELECT * FROM EMPLOYEE
WHERE JOB ='CLERK' AND SALARY < 1500;

--2.WAQTD NAME AND HIREDATE OF THE EMPLOYEES WORKING AS MANAGER IN DEPT 30.
SELECT ENAME,HIREDATE FROM EMPLOYEE
WHERE JOB = 'MANAGER' AND DEPT_NO =30;

--3.WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF THEY ARE WORKING IN DEPT 30 AS SALESMAN AND THEIR ANNUAL SALARY HAS TO BE GREATER THAN 14000. 
SELECT *,SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEE
WHERE DEPT_NO=30 AND JOB ='SALES' AND SALARY*12 >14000;

--4.WAQTD ALL THE DETAILS OF THE EMP WORKING IN DEPT 30 OR AS ANALYST. 
SELECT * FROM EMPLOYEE
WHERE DEPT_NO =30 OR JOB ='ANALYST';

--5.WAQTD NAMES OF THE EMPMLOYEES WHOS SALARY IS LESS THAN 1100 AND THEIR DESIGNATION IS CLERK. 
SELECT ENAME FROM EMPLOYEE
WHERE SALARY < 1100 AND JOB ='CLERK';

--6.WAQTD NAME AND SAL , ANNUAL SAL AND DEPTNO IF DEPTNO IS 20 EARNING MORE THAN 1100 AND ANNUAL SALARY EXCEEDS 12000.
SELECT ENAME,SALARY,SALARY*12 AS ANNUAL_SALARY,DEPT_NO FROM EMPLOYEE
WHERE DEPT_NO =20 AND SALARY >1100 AND SALARY*12 >12000

--7.WAQT EMPNO AND NAMES OF THE EMPLOYEES WORKING AS MANAGER IN DEPT 20. 
SELECT  EMP_ID,ENAME FROM EMPLOYEE
WHERE JOB='MANAGER' AND DEPT_NO =20;

--8.WAQTD DETAILS OF EMPLOYEES WORKING IN DEPT 20 OR 30 . 
SELECT * FROM EMPLOYEE
WHERE DEPT_NO  IN (20,30);

--9.WAQTD DETAILS OF EMPLOYEES WORKING AS ANALYST IN DEPT 10 .
SELECT * FROM EMPLOYEE 
WHERE JOB='ANALYST' AND DEPT_NO =10;

--10.WAQTD DETAILS OF EMPLOYEE WORKING AS PRESIDENT WITH SALARY OF RUPEES 4000. 
SELECT * FROM EMPLOYEE
WHERE JOB ='PRESIDENT' AND SALARY = 4000

--11.WAQTD NAMES AND DEPTNO , JOB OF EMPS WORKING AS CLERK IN DEPT 10 OR 20. 
SELECT ENAME,DEPT_NO FROM EMPLOYEE
WHERE JOB ='CLERK' AND DEPT_NO IN (10,20)

--12.WAQTD DETAILS OF EMPLOYEES WORKING AS CLERK OR MANAGER IN DEPT 10 .
SELECT * FROM EMPLOYEE
WHERE JOB IN ('CLERK' , 'MANAGER') AND DEPT_NO =10;

--13.WAQTD NAMES OF EMPLOYEES WORKING IN DEPT 10 , 20 , 30 , 40 .
SELECT ENAME FROM EMPLOYEE
WHERE DEPT_NO IN (10 , 20 , 30 , 40);

--14.WAQTD DETAILS OF EMPLOYEES WITH EMPNO 7902,7839. 
SELECT * FROM EMPLOYEE
WHERE EMP_ID IN (7902,7839);

--15.WAQTD DETAILS OF EMPLOYEES WORKING AS MANAGER OR SALESMAN OR CLERK. 
SELECT * FROM EMPLOYEE
WHERE JOB IN ('MANAGER' ,'SALESMAN');

--16.WAQTD NAMES OF EMPLOYEES HIRED AFTER 81 AND BEFORE 87.  
SELECT ENAME FROM EMPLOYEE
WHERE HIREDATE BETWEEN '1982-01-01' AND '1986-12-31';


--17.WAQTD DETAILS OF EMPLOYEES EARNING MORE THAN 1250 BUT LESS THAN 3000.  
SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 1250 AND 3000;

--18.WAQTD NAMES OF EMPLOYEES HIRED AFTER 81 INTO DEPT 10 OR 30.
SELECT ENAME FROM EMPLOYEE
WHERE YEAR(HIREDATE) >1981 AND DEPT_NO IN (10,30);

--19.WAQTD NAMES OF EMPLOYEES ALONG WITH ANNUAL SALARY FOR THE EMPLOYEES WORKING AS MANAGER OR CLERK INTO DEPT 10 OR 30. 
SELECT ENAME ,SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEE
WHERE JOB IN ('MANAGER','CLERK') AND DEPT_NO IN (10,30);

--20.WAQTD ALL THE DETAILS ALONG WITH ANNUAL SALARY IF SAL IS BETWEEN 1000 AND 4000 ANNUAL SALARY MORE THAN 15000.
SELECT *,SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEE
WHERE SALARY BETWEEN 1000 AND 4000
     AND SALARY*12 >15000;


-- ASSIGNMENT ON SEPCIAL OPERATORS: 

--1) LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL. 
SELECT * FROM EMPLOYEE
WHERE COMMISSION IS NULL;

--2) LIST ALL THE EMPLOYEES WHO DONT HAVE A REPORTING MANAGER. 
SELECT * FROM EMPLOYEE
WHERE MANAGER_ID IS NULL;

--3) LIST ALL THE SALESMEN IN DEPT 30. 
SELECT * FROM EMPLOYEE 
WHERE DEPT_NO =30;

--4) LIST ALL THE SALESMEN IN DEPT NUMBER 30 AND HAVING SALARY GREATER THAN 1500. 
SELECT * FROM EMPLOYEE
WHERE DEPT_NO =30 AND SALARY >1500;

--5) LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH S OR A. 
SELECT * FROM EMPLOYEE
WHERE ENAME LIKE 'S%' OR ENAME LIKE 'A%';

--6) LIST ALL THE EMPLOYEES EXCEPT THOSE WHO ARE WORKING IN DEPT 10 & 20.
SELECT * FROM EMPLOYEE 
WHERE DEPT_NO  NOT IN (10,20);

--7) LIST THE EMPLOYEES WHOSE NAME DOES NOT START WITH S. 
SELECT * FROM EMPLOYEE 
WHERE ENAME  NOT LIKE 'S%';

--8) LIST ALL THE EMPLOYEES WHO ARE HAVING  REPORTING MANAGERS IN DEPT 10. 


--9) LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL AND WORKING AS CLERK. 
SELECT * FROM EMPLOYEE
WHERE COMMISSION IS NULL AND JOB ='CLERK';

--10) LIST ALL THE EMPLOYEES WHO DONT HAVE A REPORTING MANAGER IN DEPTNO 10 OR 30. 


--11) LIST ALL THE SALESMEN IN DEPT 30 WITH SAL MORE THAN 2450. 
SELECT * FROM EMPLOYEE 
WHERE JOB ='SALESMEN' AND DEPT_NO =30 AND SALARY >2450;

--12) LIST ALL THE ANALYST IN DEPT NUMBER 20 AND HAVING SALARY GREATER THAN 2500. 
 SELECT * FROM EMPLOYEE
 WHERE DEPT_NO =20 AND SALARY >2500

--13) LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH M OR J.
SELECT * FROM EMPLOYEE
WHERE ENAME LIKE 'M%' OR ENAME LIKE 'J%';

--14) LIST ALL THE EMPLOYEES WITH ANNUAL SALARY EXCEPT THOSE WHO ARE WORKING IN DEPT 30.
SELECT *,SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEE
WHERE DEPT_NO NOT IN (30);

--15) LIST THE EMPLOYEES WHOSE NAME DOES NOT END WITH ES OR R. 
SELECT * FROM EMPLOYEE
WHERE ENAME NOT LIKE '%ES'OR ENAME NOT LIKE '%R';

--16) LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10 ALONG WITH 10% HIKE IN SALARY. 


--17) DISPLAY ALL THE EMPLOYEE WHO ARE SALESMANS HAVING E AS THE LAST BUT ONE CHARACTER IN ENAME BUT SALARY HAVING EXACTLY 4 CHARACTER.
SELECT * FROM EMPLOYEE
WHERE JOB='SALESMAN' AND  ENAME LIKE '%E_' AND SALARY LIKE '____';

--18) DISPLAY ALL THE EMPLOYEE WHO ARE JOINED AFTER YEAR 81.
SELECT * FROM EMPLOYEE
WHERE YEAR(HIREDATE)>81;

--19) DISPLAY ALL THE EMPLOYEE WHO ARE JOINED IN FEB. 
SELECT * FROM EMPLOYEE
WHERE MONTH(HIREDATE) = 02;

--20) LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGERS AND CLERKS IN DEPT 10 AND 20 WITH A SALARY IN THE RANGE OF 1000 TO 3000. 
SELECT * FROM EMPLOYEE
WHERE JOB NOT IN ('MANAGERS','CLERKS') AND 
DEPT_NO  IN(10,20) AND SALARY BETWEEN 1000 AND 3000






